language: ruby
rvm:
- 2.2
env:
  global:
  - secure: "HOUyVR1hQ6wqBvv3EQEAe8+Fvlb6TwkkqQUTpOGDDpskxr0qGIkYvsjUAxEEJBkIr2R2AxNr0PyFIGtz2IIoYvqGLshULeXzLg4SAiL0YzeRyreex5osS8Au7lVmqx627M4JMEgfHanplpCRYGlWf+QXIO20U+hSRwsc+Zx/u/c="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
