language: ruby
rvm:
- 2.2
env:
  global:
  - secure: "Ds8aBqDwqeL6jkvbdJACHgtZX2Rocss19jwhc0q1VpJnpBBPvhYZpCaGa4AoR+TL93tKUbm4zBODJoLdFbj0qEeA2poXKBgftkkv2GUf5XIovZmBk/mQVIgiDD0GTkJkhismQV4irC2VRU20nQvwFyqxYgJTnnpEX/By2X65fM0="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
