language: ruby
rvm:
- 2.2
env:
  global:
  - secure: IJEFYavnOwahY5f7M98uJPmFi4u95k56leENixW5kMq34DIBDkR38no0oMItxBfSM0VGnIrnSyrRHdjMJTOrxiWpP7qLd8j7wQZXr92tR2sUJtAFGOrOZ7KPqdnBCS3aYTTIJfb0c2ayLjtPC02MS+6QLuIDC/NK/or3eseyNWI=
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk MAILOSAUR_SMTP_PORT=12525
notifications:
  webhooks: https://outlook.office365.com/webhook/15b4ba90-3687-4f64-9426-614ddf100184@d49da0b1-9141-48b1-b00d-58ac067d4cf4/TravisCI/cf68bf17b0484bfe8df7b29e98b26abc/f414b2da-0704-4552-a65a-2116b8b3d218